import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface PDFData {
  role: string;
  difficulty: string;
  date: string;
  overallScore: number;
  metrics: {
    technicalAccuracy: number;
    communication: number;
    problemSolving: number;
    confidence: number;
  };
  strengths: string[];
  growthAreas: string[];
  finalVerdict: string;
  questionBreakdown: {
    question: string;
    userAnswer: string;
    expectedAnswer: string;
    feedback: string;
  }[];
}

export const generateInterviewPDF = (data: PDFData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;

  // --- HEADER & BRANDING ---
  doc.setFillColor(31, 41, 55); // Dark gray header
  doc.rect(0, 0, pageWidth, 40, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("INTERVIEW BATTLEFIELD AI", margin, 25);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("PRO-LEVEL TECHNICAL ASSESSMENT REPORT", margin, 33);

  // --- SESSION INFO ---
  let y = 55;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("EXECUTIVE SUMMARY", margin, y);
  
  y += 10;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Candidate Role: ${data.role}`, margin, y);
  doc.text(`Assessment Date: ${new Date(data.date).toLocaleDateString()}`, pageWidth - margin - 50, y);
  
  y += 6;
  doc.text(`Difficulty Level: ${data.difficulty}`, margin, y);
  
  y += 15;
  
  // --- OVERALL SCORE SECTION ---
  doc.setFillColor(243, 244, 246); // Light gray bg
  doc.roundedRect(margin, y, pageWidth - (margin * 2), 30, 3, 3, "F");
  
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(37, 99, 235); // Blue
  doc.text(`${data.overallScore}/100`, margin + 10, y + 18);
  
  doc.setFontSize(10);
  doc.setTextColor(107, 114, 128);
  doc.text("OVERALL PERFORMANCE SCORE", margin + 10, y + 25);

  // METRICS
  const metricX = margin + 80;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(9);
  doc.text(`Technical Accuracy: ${data.metrics.technicalAccuracy}%`, metricX, y + 10);
  doc.text(`Communication: ${data.metrics.communication}%`, metricX + 50, y + 10);
  doc.text(`Problem Solving: ${data.metrics.problemSolving}%`, metricX, y + 20);
  doc.text(`Confidence Level: ${data.metrics.confidence}%`, metricX + 50, y + 20);

  y += 45;

  // --- STRENGTHS & WEAKNESSES ---
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("KEY STRENGTHS", margin, y);
  y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  data.strengths.forEach((s) => {
    const text = doc.splitTextToSize(`• ${s}`, pageWidth - (margin * 2));
    doc.text(text, margin, y);
    y += (text.length * 5);
  });

  y += 10;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("AREAS FOR GROWTH", margin, y);
  y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  data.growthAreas.forEach((w) => {
    const text = doc.splitTextToSize(`• ${w}`, pageWidth - (margin * 2));
    doc.text(text, margin, y);
    y += (text.length * 5);
  });

  y += 15;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("FINAL VERDICT", margin, y);
  y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const verdictText = doc.splitTextToSize(data.finalVerdict, pageWidth - (margin * 2));
  doc.text(verdictText, margin, y);
  y += (verdictText.length * 5) + 15;

  // --- DETAILED QUESTION REVIEW (TABLE) ---
  doc.addPage();
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("DETAILED INTERVIEW BREAKDOWN", margin, 20);

  const tableData = data.questionBreakdown.map((item, index) => [
    `Q${index + 1}: ${item.question}\n\nYOUR ANSWER: ${item.userAnswer}\n\nIDEAL ANSWER: ${item.expectedAnswer}\n\nAI FEEDBACK: ${item.feedback}`
  ]);

  autoTable(doc, {
    startY: 30,
    head: [["QUESTION & COMPREHENSIVE FEEDBACK"]],
    body: tableData,
    styles: {
      fontSize: 9,
      cellPadding: 8,
      overflow: "linebreak",
      lineWidth: 0.1,
      lineColor: [229, 231, 235],
    },
    headStyles: {
      fillColor: [31, 41, 55],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251],
    },
  });

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(
      `Generated by Interview Battlefield AI • Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  doc.save(`Interview_Report_${data.role.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.pdf`);
};
